name: Build Releases

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary_name: FGOL
            artifact_name: fgol-linux
      
          - os: windows-latest
            binary_name: FGOL.exe
            artifact_name: fgol-win
      
          - os: macos-latest
            binary_name: FGOL
            artifact_name: fgol-macos

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build release
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: target/release/${{ matrix.binary_name }}
